chore: Add license and other fields in the `package.json` file
web3community/devprotocol.xyz pull request #108
Opened 2021-11-07 03:36 UTC by Panquesito7

#### Description of the change

- Add license and other fields in the `package.json` file.

#### Checklist

- [x] Added description of the change
- [x] I've read the [contributing guidelines](https://github.com/web3community/devprotocol.xyz/blob/main/CONTRIBUTING.md)
- [x] Search previous suggestions before making a new PR, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes (**optional**):

2021-11-07 06:55 UTC, krishguptadev requested changes

2021-11-07 06:55 UTC, krishguptadev commented on package.json
> +  "private": false,
If it is not private it can be published to non registery.

```suggestion
  "private": true,
```

2021-11-07 06:55 UTC, krishguptadev commented on package.json
> +  "main": "layouts/Default.astro",
This can't be run via node. Thus,

```suggestion
```

2021-11-08 03:21 UTC, krishguptadev approved these changes

2021-11-08 04:26 UTC, vinzvinci approved these changes

2021-11-08 04:26 UTC, merged